name = "espn-fbe"
main = "src/index.js"
compatibility_date = "2022-07-31"

# [triggers]
# crons = [ "0 */1 * * SUN" ]

# The necessary secrets are:
[vars]
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these